name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt install yarn
      
    - name: Install palava-web
      run: yarn

    - name: Lint palava-web
      run: yarn lint
    
    - name: Audit palava-web
      run: yarn audit --groups dependencies